config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'movies/index'
  get 'movies/show'
  root to: 'lists#index'
  resources :lists, except: [:edit, :update, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Crear un marcador</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, prompt: 'select a movie' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <div class="navbar navbar-dark bg-dark">
      <div class="logo text-white">
        <P>Peliculas Ruby</P>
      </div>
      <div class="links">
        <%= link_to lists_path, { class: "btn btn-primary" } do %>
        <span class="label label-primary">Home</span>
        <% end %>
      </div>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/lists/index.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark d-flex justify-content-between text-primary">
    <h1 class="">Pelis</h1>

    <div class="i-movie d-flex align-items-center ">
        <%= link_to  "Crear Lista", new_list_path, class: 'btn btn-lg btn-outline-success mr-5' %>
        <i class="fas fa-3x fa-film "></i>
    </div>
</div>

<div class="container">
    <div class="sub-title text-center">
        <h3 class="mt-5">My Lists</h3>
        <%  %>
    </div>
</div>

<div class="container d-flex">
    <% @lists.each do |list| %>
        <div class="card m-3" style="width: 18rem; ">
            <%= cl_image_tag list.photo.key, crop: :fill, class: 'h-50' %>
            <%= link_to  list.name.capitalize, list_path(list), class: 'card-body text-center text-decoration-none' %>
        </div>
    <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="text-center p-4">Crear una lista</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file%>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">

    <h2 class= "text-center p-3"><%= @list.name.capitalize %> </h2>

  <div class="container d-flex flex-row-reverse">

    <%= link_to  lists_path do %>
      <span><i class="p-2 fas fa-3x fa-arrow-alt-circle-left"></i></span>
    <% end %>
    <%= link_to new_list_bookmark_path(@list) do %>
      <span> <i class="p-2 fas fa-3x fa-plus-square"></i></span>
    <% end %>

  </div>

    

    <div class="card " style="width: 18rem;">
        <% @list.movies.each do |movie| %>
            <%= image_tag movie.poster_url %>
            <h3><%= movie.title  %></h3>
            <p><%= movie.overview %></p>
            <p><%= movie.rating %></p> 
        <% end %>
    </div>
</div>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>